version: "3"
   
services:
  db:
    image: postgres
    container_name: postgresql
    environment:
      - POSTGRES_DB=DjangoOfficialTuto
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=5432
    ports:
      - "32768:5432"
    restart: always
  web:
    build: .
    container_name: DjangoOfficialTuto_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
